kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-name
  namespace: default-new
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
